SELECT TOP (1000) [FactTablePK]
      ,[dimPatientPK]
      ,[dimPhysicianPK]
      ,[dimDatePostPK]
      ,[dimDateServicePK]
      ,[dimCPTCodePK]
      ,[dimPayerPK]
      ,[dimTransactionPK]
      ,[dimLocationPK]
      ,[PatientNumber]
      ,[dimDiagnosisCodePK]
      ,[CPTUnits]
      ,[GrossCharge]
      ,[Payment]
      ,[Adjustment]
      ,[AR]
  FROM [Healthcare_DB].[dbo].[FactTable]
